/* Auto-generated by scripts/generate-forum-posts.mjs — do not edit by hand. */
import type { BlogPostDefinition } from './types';

export const blogPosts: BlogPostDefinition[] = [
	{
		id: "install-guide",
		imageKey: "hacksPackage",
		published: "2026-08-12",
		updated: "2026-09-10",
		category: "Setup",
		featured: true,
		translations: {
		en: {
		slug: "how-to-install-dota-2-cheats-windows",
		title: "How to Install Dota 2 Cheats on Windows PC",
		metaDescription: "Step-by-step dota 2 cheats install for Windows 10 and 11. Download, license key, ESP overlay, and first launch checklist before ranked.",
		h1: "How to Install Dota 2 Cheats on Windows PC",
		intro: "First time setting up a dota 2 cheat package? This walkthrough covers download, license activation, overlay launch, and the three settings I always change before queuing.",
		keywords: ["dota 2 cheats install","dota 2 hack setup","dota 2 esp setup"],
		imageAlt: "Dota 2 cheats installer screen on Windows PC",
		sections: [
			{
				h2: "Before you download anything",
				paragraphs: [
					"Close Steam completely, disable any leftover overlay apps, and run the installer as admin. Windows Defender will flag most cheat loaders — add the install folder to exclusions before you extract files.",
					"Grab your license from the email receipt. Keys are single-seat; do not share them in Discord DMs asking for \"help.\"",
				],
			},
			{
				h2: "Launch order that actually works",
				paragraphs: [
					"Open the loader first, paste the key, wait for the green status light, then start Dota 2. Inject after the main menu loads — not during the Valve splash.",
					"Toggle ESP on low opacity for the first match. Cranking every slider day one is how people clip themselves on stream by accident.",
				],
			}
		],
		comments: [
			{ author: "stack_player", date: "2026-08-14", body: "took me two tries bc i launched dota before the loader. this order fixed it" },
			{ author: "mid_or_feed", date: "2026-08-14", body: "works on win11 23h2 for me. defender exclusion is mandatory tho" },
			{ author: "ancient_5", date: "2026-08-15", body: "my key said already used, support swapped it in like 20 min. annoying but they fixed it" },
			{ author: "ward_boy", date: "2026-08-16", body: "solid guide. wish the loader had a verify button before inject" }
		],
		},
		},
	},
	{
		id: "esp-settings-ranked",
		imageKey: "playerEsp",
		published: "2026-08-18",
		updated: "2026-09-12",
		category: "ESP",
		featured: true,
		translations: {
		en: {
		slug: "dota-2-esp-settings-ranked-matches",
		title: "Dota 2 ESP Settings: What Works Best in Ranked?",
		metaDescription: "Dota 2 ESP settings for ranked — hero boxes, ward vision, rune timers, and opacity levels that stay readable without cluttering your screen.",
		h1: "Dota 2 ESP Settings: What Works Best in Ranked?",
		intro: "Ranked ESP is not about seeing everything — it is about seeing the right things at the right time. Here is how I run hero ESP, ward dots, and courier tags without turning the screen into a Christmas tree.",
		keywords: ["dota 2 esp settings","dota 2 esp ranked","dota 2 wallhack settings"],
		imageAlt: "Dota 2 ESP settings panel with hero overlay toggles",
		sections: [
			{
				h2: "Hero ESP vs map clutter",
				paragraphs: [
					"Keep enemy hero boxes at 70% opacity and disable ally skeletons unless you play support. Distance tags past 3000 units are noise in lane.",
					"Ward ESP saved me more MMR than any aim feature. Set ward dots to pulse only when within smoke range.",
				],
			},
			{
				h2: "Profiles per role",
				paragraphs: [
					"Mid profile: skillshot assist low, ESP high, minimap radar medium. Hard support: ward vision max, hero ESP medium, courier tag on.",
					"Save profiles per hero if you swap roles. Copying a carry config on Rubick feels awful.",
				],
			}
		],
		comments: [
			{ author: "pos4_grinder", date: "2026-08-19", body: "ward esp alone worth the sub. finally dewarding spots i never checked" },
			{ author: "toxic_archon", date: "2026-08-20", body: "too much opacity and teammates asked if my monitor was broken lol" },
			{ author: "smurf_again", date: "2026-08-21", body: "ranked feels smoother at 60% box opacity. trust" }
		],
		},
		},
	},
	{
		id: "aimbot-settings-ban",
		imageKey: "aimbotCombat",
		published: "2026-08-22",
		updated: "2026-09-14",
		category: "Aimbot",
		featured: true,
		translations: {
		en: {
		slug: "skillshot-assist-settings-level-why-wont-i-get-banned",
		title: "Skillshot Assist Settings: What Level & Why Won't I Get Banned?",
		metaDescription: "Dota 2 skillshot assist settings explained — smoothing, FOV, and humanizer sliders. What levels look natural and how VAC flags obvious automation.",
		h1: "Skillshot Assist Settings: What Level & Why Won't I Get Banned?",
		intro: "Everyone asks the same question in every cheat Discord: \"what slider gets me banned?\" Short answer: max everything and clip it on TikTok. Long answer: here is what I run on Invoker, Pudge, and Mirana without looking like a bot.",
		keywords: ["dota 2 aimbot settings","dota 2 skillshot assist","dota 2 hack ban"],
		imageAlt: "Dota 2 skillshot assist FOV and smoothing sliders",
		sections: [
			{
				h2: "Smoothing beats raw snap",
				paragraphs: [
					"Humanizer at 65–75% with FOV under 12 degrees looks like a good player on a lucky day. Instant snap hooks across the map are how you get reported nine times in one game.",
					"VAC does not read your chat. It reads patterns. Randomize reaction delay between 80–140 ms on skillshot assist.",
				],
			},
			{
				h2: "Hero-specific caps",
				paragraphs: [
					"Pudge: medium assist, manual finish on clutch hooks. Invoker: only Sun Strike assist, not full combo scripts in ranked.",
					"If you climb two ranks in a week, tone it down. Players notice before Valve does.",
				],
			}
		],
		comments: [
			{ author: "hook_sniper", date: "2026-08-23", body: "dropped fov to 10 and reports stopped. still hitting hooks just not circus ones" },
			{ author: "vac_wave_survivor", date: "2026-08-24", body: "got hit on a different provider last year. this build survived march patch for me" },
			{ author: "legit_dealer", date: "2026-08-25", body: "humanizer at 50 feels sluggish. 70 is the sweet spot for me" },
			{ author: "mad_support", date: "2026-08-26", body: "stop using max assist on rubick stuns. you are not fooling anyone" },
			{ author: "chart_watcher", date: "2026-08-27", body: "good thread. saved my smurf from looking like a script kiddie" }
		],
		},
		},
	},
	{
		id: "features-breakdown",
		imageKey: "espWallhack",
		published: "2026-08-25",
		updated: "2026-09-08",
		category: "Features",
		featured: false,
		translations: {
		en: {
		slug: "dota-2-cheats-features-full-breakdown",
		title: "Dota 2 Cheats Features — Full Breakdown",
		metaDescription: "Every dota 2 cheats feature explained — ESP, maphack, skillshot assist, auto last hit, camera hack, radar, and combo scripts. What each toggle does in match.",
		h1: "Dota 2 Cheats Features — Full Breakdown",
		intro: "Marketing pages list features in bullet points. This thread explains what each toggle actually does in a real ranked game, and which ones I leave off.",
		keywords: ["dota 2 cheats features","dota 2 hack features","dota 2 esp aimbot"],
		imageAlt: "Dota 2 cheats feature list with ESP and maphack toggles",
		sections: [
			{
				h2: "Vision tools",
				paragraphs: [
					"Hero ESP, ward vision, rune timers, and courier tracking fall under vision. Maphack draws jungle camps and enemy last-known positions through fog.",
					"Radar overlay mirrors minimap threats with audio pings — optional but strong for offlaners.",
				],
			},
			{
				h2: "Mechanical assists",
				paragraphs: [
					"Skillshot assist, auto last hit, combo scripts, and armlet toggle helpers are mechanical. Higher risk, higher reward.",
					"Camera distance hack is subtle if you stay within 10% of default. Stretch to moon view and everyone knows.",
				],
			}
		],
		comments: [
			{ author: "feature_guy", date: "2026-08-26", body: "combo script for meepo is insane but drains fps on older laptops" },
			{ author: "carry_only", date: "2026-08-27", body: "auto last hit at 85% feels legit. 100% looks robotic in replays" },
			{ author: "salty_legend", date: "2026-08-28", body: "half these toggles are gimmicks. esp + wards is 90% of value" }
		],
		},
		},
	},
	{
		id: "maphack-vs-wards",
		imageKey: "raidMapMap",
		published: "2026-08-28",
		updated: "2026-09-11",
		category: "Maphack",
		featured: false,
		translations: {
		en: {
		slug: "maphack-vs-ward-vision-difference",
		title: "Maphack vs Ward Vision — What's the Difference?",
		metaDescription: "Dota 2 maphack vs ward ESP explained. Fog removal, hero positions, and which setting gives better info for dewarding and ganks.",
		h1: "Maphack vs Ward Vision — What's the Difference?",
		intro: "New buyers toggle both and wonder why the screen looks wrong. Maphack and ward vision solve different problems — here is when to use each.",
		keywords: ["dota 2 maphack","dota 2 ward hack","dota 2 wallhack"],
		imageAlt: "Dota 2 maphack fog removal compared to ward ESP dots",
		sections: [
			{
				h2: "Maphack draws geometry",
				paragraphs: [
					"Maphack removes fog of war on terrain and shows enemy heroes last seen on map. It does not replace true vision — you still cannot see invisible heroes without sentries.",
					"Best for rotations and smoke breaks. Terrible if you stare at map instead of lane creeps.",
				],
			},
			{
				h2: "Ward vision is precision",
				paragraphs: [
					"Ward ESP highlights observer and sentry wards through trees. Pair with dewarding range indicator for offlane wins.",
					"I run ward vision always, maphack only on supports and initiators.",
				],
			}
		],
		comments: [
			{ author: "offlane_king", date: "2026-08-29", body: "ward esp > maphack for climbing. learned that the hard way" },
			{ author: "map_stare", date: "2026-08-30", body: "maphack got me killed more bc i stopped watching lane. user error tbh" }
		],
		},
		},
	},
	{
		id: "auto-last-hit",
		imageKey: "aimbotSkeleton",
		published: "2026-09-01",
		updated: "2026-09-13",
		category: "Scripts",
		featured: false,
		translations: {
		en: {
		slug: "auto-last-hit-script-natural-settings",
		title: "Auto Last Hit Script: Settings That Actually Feel Natural",
		metaDescription: "Dota 2 auto last hit script settings for lane — miss rate, attack move delay, and deny assist. Stay believable while securing CS.",
		h1: "Auto Last Hit Script: Settings That Actually Feel Natural",
		intro: "Perfect last hit scripts exist. Perfect last hit scripts also get you reported by your own team. Here is how I miss a creep on purpose sometimes.",
		keywords: ["dota 2 auto last hit","dota 2 scripts","dota 2 cheat lane"],
		imageAlt: "Dota 2 auto last hit script timing settings",
		sections: [
			{
				h2: "Miss rate matters",
				paragraphs: [
					"Set intentional miss rate to 8–12% on ranged carries. Melee can run tighter because attack anims hide timing.",
					"Deny assist should be lower priority than last hits — obvious deny scripts are meme clips.",
				],
			}
		],
		comments: [
			{ author: "cs_student", date: "2026-09-02", body: "12% miss still averages better than my hands at 3am" },
			{ author: "mid_gap", date: "2026-09-03", body: "deny assist too obvious in replays. turned off" },
			{ author: "lane_bully", date: "2026-09-04", body: "works on win10. broke once after sept patch, update fixed next day" },
			{ author: "free_cookies", date: "2026-09-05", body: "not worth on invoker. just practice" }
		],
		},
		},
	},
	{
		id: "camera-hack",
		imageKey: "headerArt",
		published: "2026-09-03",
		updated: "2026-09-14",
		category: "Camera",
		featured: false,
		translations: {
		en: {
		slug: "camera-hack-distance-how-far-is-too-far",
		title: "Camera Hack Distance: How Far Is Too Far?",
		metaDescription: "Dota 2 camera hack distance settings — zoom limits, default comparison, and what enemies notice in ranked replays.",
		h1: "Camera Hack Distance: How Far Is Too Far?",
		intro: "Camera distance is the most subtle cheat until it is not. This thread covers safe zoom ranges and why your offlane feels different at +15%.",
		keywords: ["dota 2 camera hack","dota 2 zoom hack","dota 2 cheats camera"],
		imageAlt: "Dota 2 camera distance hack slider comparison",
		sections: [
			{
				h2: "Safe zoom bands",
				paragraphs: [
					"Stay within 5–10% above default for ranked. Tournament players use high camera too — abuse that cover story.",
					"Beyond 15% you see rune spawns early and off-screen ganks. Teammates with replays will clock it.",
				],
			}
		],
		comments: [
			{ author: "zoomer", date: "2026-09-04", body: "8% is my cap. anything more feels like playing a different game" },
			{ author: "replay_hunter", date: "2026-09-05", body: "saw a guy on 20% in legend. whole team flamed him in all chat" }
		],
		},
		},
	},
	{
		id: "patch-fix",
		imageKey: "squadFight",
		published: "2026-09-05",
		updated: "2026-09-15",
		category: "Troubleshooting",
		featured: false,
		translations: {
		en: {
		slug: "cheat-stopped-working-after-patch-fix",
		title: "Why My Cheat Stopped Working (And How I Fixed It)",
		metaDescription: "Dota 2 cheat not working after patch — loader errors, VAC update, overlay crash fixes. Checklist before opening a support ticket.",
		h1: "Why My Cheat Stopped Working (And How I Fixed It)",
		intro: "Patch day panic thread. If ESP vanished mid-session, work through this list before blaming the license.",
		keywords: ["dota 2 cheat not working","dota 2 hack patch","dota 2 vac update"],
		imageAlt: "Dota 2 cheat loader error after game patch",
		sections: [
			{
				h2: "Patch day checklist",
				paragraphs: [
					"Check the status page first. If build is red, wait — injecting into outdated client is how you force a restart loop.",
					"Delete old config JSON after major patches. Sliders from last meta sometimes crash overlay init.",
				],
			}
		],
		comments: [
			{ author: "panic_queue", date: "2026-09-06", body: "status page said wait 4 hrs. worked after rebuild. patience" },
			{ author: "old_config", date: "2026-09-07", body: "deleting config fixed crash on launch. should be in pin" },
			{ author: "refund_threat", date: "2026-09-08", body: "took 6 hours last patch. annoying but came back" },
			{ author: "linux_guy", date: "2026-09-09", body: "doesnt work on linux. vm only. wish i knew earlier" },
			{ author: "fixed_it", date: "2026-09-10", body: "reinstall loader only, not whole game. saved time" }
		],
		},
		},
	},
	{
		id: "monthly-vs-lifetime",
		imageKey: "hacksPackage",
		published: "2026-09-07",
		updated: "2026-09-12",
		category: "Pricing",
		featured: false,
		translations: {
		en: {
		slug: "monthly-vs-lifetime-license-worth-it",
		title: "Monthly vs Lifetime License — Worth It?",
		metaDescription: "Dota 2 cheats monthly vs lifetime license comparison. Break-even math, patch support, and which plan fits casual vs daily ranked grinders.",
		h1: "Monthly vs Lifetime License — Worth It?",
		intro: "Lifetime looks expensive until you do the math. Monthly looks cheap until you forget to cancel for eight months.",
		keywords: ["dota 2 cheats price","dota 2 hack monthly","dota 2 cheats lifetime"],
		imageAlt: "Dota 2 cheats monthly and lifetime pricing comparison",
		sections: [
			{
				h2: "Break-even at month five",
				paragraphs: [
					"$35 monthly vs $150 lifetime — lifetime wins if you play two seasons. Casual weekend warriors should stay monthly.",
					"Both tiers get same features. Lifetime is not a separate build.",
				],
			}
		],
		comments: [
			{ author: "budget_mike", date: "2026-09-08", body: "monthly for me. play 2 weekends a month" },
			{ author: "daily_grind", date: "2026-09-09", body: "lifetime paid off in 4 months. no brainer if you queue daily" },
			{ author: "skeptic_sam", date: "2026-09-10", body: "worried provider dies before lifetime pays off. monthly feels safer" }
		],
		},
		},
	},
	{
		id: "radar-hack",
		imageKey: "raidCombat",
		published: "2026-09-09",
		updated: "2026-09-14",
		category: "Radar",
		featured: false,
		translations: {
		en: {
		slug: "radar-hack-missing-enemies-minimap",
		title: "Radar Hack for Missing Enemies on Map",
		metaDescription: "Dota 2 radar hack setup — minimap pings, missing hero alerts, and audio cues when enemies leave lane. Config for supports and mids.",
		h1: "Radar Hack for Missing Enemies on Map",
		intro: "Maphack shows fog. Radar tells you someone left lane three seconds ago. Different tools — here is my radar config.",
		keywords: ["dota 2 radar hack","dota 2 esp minimap","dota 2 cheats radar"],
		imageAlt: "Dota 2 radar hack minimap enemy ping overlay",
		sections: [
			{
				h2: "Audio vs visual pings",
				paragraphs: [
					"Visual-only radar is easy to miss in team fights. I run soft audio ping on missing mid and jungler crossing river.",
					"Disable ally false positives — courier and illusions spam the log otherwise.",
				],
			}
		],
		comments: [
			{ author: "support_main", date: "2026-09-10", body: "audio ping saved so many ganks. underrated feature" },
			{ author: "turned_off", date: "2026-09-11", body: "too noisy with naga illusions. needs filter" },
			{ author: "mid_life", date: "2026-09-12", body: "pair with ward esp. radar alone not enough high mmr" }
		],
		},
		},
	},
	{
		id: "meepo-combo",
		imageKey: "raidFight",
		published: "2026-09-11",
		updated: "2026-09-15",
		category: "Combo Scripts",
		featured: false,
		translations: {
		en: {
		slug: "meepo-combo-script-setup-guide",
		title: "Meepo Combo Scripts — Setup Guide",
		metaDescription: "Dota 2 meepo combo script setup — poof chains, tab cycle, and fail-safes. Settings that work in ranked without locking your screen.",
		h1: "Meepo Combo Scripts — Setup Guide",
		intro: "Meepo is the reason combo scripts exist. This is how I bound poof chains without fat-fingering buyback.",
		keywords: ["dota 2 meepo script","dota 2 combo script","dota 2 cheats meepo"],
		imageAlt: "Dota 2 meepo combo script keybind configuration",
		sections: [
			{
				h2: "Keybind layout",
				paragraphs: [
					"One key for net + poof, separate key for hex focus. Never bind full burst to spacebar — you will panic press it in fountain.",
					"Human delay between poofs at 40–60 ms looks cleaner on replay than instant frame-perfect chains.",
				],
			}
		],
		comments: [
			{ author: "meepo_one", date: "2026-09-12", body: "finally hit 5k after script setup. still miss manual poofs sometimes lol" },
			{ author: "anti_script", date: "2026-09-13", body: "scripts ruin the hero. learn poofs" },
			{ author: "lag_spike", date: "2026-09-14", body: "script desynced on 120 ping. fine on 30" }
		],
		},
		},
	},
	{
		id: "vac-maintenance",
		imageKey: "hero",
		published: "2026-09-13",
		updated: "2026-09-16",
		category: "VAC",
		featured: false,
		translations: {
		en: {
		slug: "vac-update-what-to-do-before-ranked",
		title: "VAC Update: What to Do Before Queuing Ranked",
		metaDescription: "Dota 2 VAC update checklist for cheat users — when to wait, how to verify build status, and safe relaunch steps after Valve patches.",
		h1: "VAC Update: What to Do Before Queuing Ranked",
		intro: "Valve pushed a client update at 2am and half the forum is in meltdown. Read this before you inject and blame the loader.",
		keywords: ["dota 2 vac update","dota 2 cheat vac","dota 2 hack ban risk"],
		imageAlt: "Dota 2 VAC update status check before launching cheats",
		sections: [
			{
				h2: "Wait for green status",
				paragraphs: [
					"Status page green means tested against current client. Yellow means use at own risk. Red means close the loader and touch grass.",
					"Do not run old loader versions \"because it worked yesterday.\" That is how accounts get flagged.",
				],
			}
		],
		comments: [
			{ author: "patient_zero", date: "2026-09-14", body: "waited 3 hrs after vac notes. no issues since" },
			{ author: "impatient", date: "2026-09-15", body: "injected on yellow. worked but wont risk again" },
			{ author: "banned_2024", date: "2026-09-15", body: "learned this after a 6 month ban on another tool. not worth rushing" },
			{ author: "status_watcher", date: "2026-09-16", body: "discord ping when green would be nice. had to refresh page all day" }
		],
		},
		},
	}
];
